apiVersion: gateway.kyma-project.io/v1alpha2
kind: Api
metadata:
  name: {{ .Release.Name | trunc 32 | trimSuffix "-" }}
  labels:
    app: {{ include "github-connector-chart.name" . }}
    chart: {{ include "github-connector-chart.chart" . }}
    release: {{ .Release.Name | trunc 32 | trimSuffix "-" }}
    heritage: {{ .Release.Service | trunc 32 | trimSuffix "-" }}
spec:
    service:
      name: {{ .Release.Name }}
      port: {{ .Values.service.port }}
    hostname: {{ .Release.Name | trunc 32 | trimSuffix "-" }}.{{ .Values.kymaAddress }}