apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ printf "%s-%s" .Release.Name "serviceinstance-reader" | trunc 63 | trimSuffix "-" }}
  namespace: test #

rules:
- apiGroups: ["servicecatalog.k8s.io"]
  resources: ["serviceinstances"]
  verbs: ["get", "watch", "list", "describe"]